spring:
  datasource:
    url: jdbc:postgresql://db:5432/cymes
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

show-scheduler:
  cinema-hall-cleaning-time: PT30M
  commercials-display-time: PT30M