spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://db:5432/cymes
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

show-scheduler:
  cinema-hall-cleaning-time: PT30M
  commercials-display-time: PT30M

jwt:
  secret: E(H+MbQeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+KaPdSgVkYp3s6v9y
  token-expires-after: PT15M

ticket-prices: '{
  JUNIOR: 25,
  REGULAR: 40,
  STUDENT: 20,
  SENIOR: 30
}'